project:
  type: website
  preview:
        port: 8888

website:
  title: "offetam.github.io"
  navbar:
    tools:
      - icon: github
        href: https://github.com/offetam/offetam.github.io
    left:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: Blog
    right:
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

